# Development environment configuration

spring:
  datasource:
    url: jdbc:h2:mem:devdb
    username: sa
    password: password
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

# Development-specific settings
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Enhanced logging for development
logging:
  level:
    com.javamastery.ecommerce: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Development-specific circuit breaker settings
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 60

# Development JWT settings (shorter expiration for testing)
jwt:
  secret: devSecretKey123456789012345678901234567890
  expiration: 3600000  # 1 hour