server:
  port: 8085

spring:
  application:
    name: notification-service
  
  datasource:
    url: jdbc:h2:mem:notificationdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # Mail Configuration (for simulation)
  mail:
    host: smtp.gmail.com
    port: 587
    username: simulation@example.com
    password: simulation-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000

# Notification Configuration
notification:
  email:
    enabled: true
    simulation-mode: true  # Set to false to send real emails
    from-address: notifications@ecommerce.com
    from-name: E-commerce Platform
  sms:
    enabled: true
    simulation-mode: true  # Set to false to send real SMS
    provider: twilio
  template:
    base-path: classpath:/templates/
  retry:
    max-attempts: 3
    delay-ms: 1000

logging:
  level:
    com.javamastery.ecommerce.notification: DEBUG

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html