spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format-sql: true
    
  datasource:
    url: jdbc:h2:mem:devdb
    username: sa
    password: password
    
  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  level:
    com.javamastery.taskapi: DEBUG